version: '3'
services:
  web:
    image:  "hello_swarm:latest"
    ports:
      - "5000:5000"
    deploy:
      replicas: 5
      resources:
        limits:
          cpus: "0.1"
          memory: 50M
      restart_policy:
        condition: on-failure
    networks:
      - webnet
  redis:
    image: "redis:alpine"
    networks:
      - webnet
networks:
  webnet: